//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShivaRestaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tablebooking
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Telephone { get; set; }
        public System.DateTime Reserve_Date { get; set; }
        public string Reserve_Time { get; set; }
        public Nullable<int> Persons_Count { get; set; }
    }
}
